# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yottatide.com
title: <img src="img/logo.png" id="logo">
email: your-email@domain.com
author: YottaTide
description: > # "Write an awesome description for your new site here.
  You can edit this line in _config.yml. It will appear in your document
  head meta (for Google search results) and in your feed.xml site
  description.
copyright: 'Copyright &copy; 2017 YottaTide. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/YottaTide
  - title: facebook
    url: https://facebook.com/YottaTide
